apiVersion: v1
kind: Service
metadata:
  name: phpadmin
  namespace: openldap
  labels:
    app.kubernetes.io/name: phpadmin
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: phpadmin
