# storageclass.yaml
# StorageClass for /tank/data/k8s-volumes backend
# Naming convention: nfs-<backend-path-name>
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-k8s-volumes
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate