apiVersion: v1
kind: Namespace
metadata:
  name: lldap
  labels:
    name: lldap
    app.kubernetes.io/name: lldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure