apiVersion: v1
kind: Service
metadata:
  name: lldap-ldaps
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  type: LoadBalancer
  ports:
  - name: ldaps
    port: 636
    targetPort: 6636
    protocol: TCP
  selector:
    app.kubernetes.io/name: lldap