apiVersion: v1
kind: Service
metadata:
  name: lldap-web
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 17170
    targetPort: 17170
    protocol: TCP
  selector:
    app.kubernetes.io/name: lldap