apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-kojigenba-srv-com-tls
  namespace: openldap
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  secretName: ldap-kojigenba-srv-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ldap.kojigenba-srv.com
  - phpadmin.kojigenba-srv.com
  usages:
  - digital signature
  - key encipherment
  - server auth