apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data-pvc
  namespace: openldap
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-volumes
  resources:
    requests:
      storage: 5Gi