apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-archive-pv
  labels:
    app.kubernetes.io/name: samba
    app.kubernetes.io/component: storage
    storage-type: nfs-archive
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-archive-static
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
  nfs:
    server: 192.168.10.11
    path: /mnt/sdc/archive
