apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-shared-storage
  namespace: samba
  labels:
    app.kubernetes.io/name: samba
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared
  resources:
    requests:
      storage: 1.5Ti
