apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-archive-storage
  namespace: samba
  labels:
    app.kubernetes.io/name: samba
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-archive-static
  volumeName: samba-archive-pv
  resources:
    requests:
      storage: 6Ti
