apiVersion: v1
kind: Service
metadata:
  name: samba-smb
  namespace: samba
  labels:
    app.kubernetes.io/name: samba
    app.kubernetes.io/component: file-sharing
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.103
  ports:
  - name: smb
    port: 445
    targetPort: 445
    protocol: TCP
  selector:
    app.kubernetes.io/name: samba
