apiVersion: v1
kind: Service
metadata:
  name: lldap-ldap
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: authentication-infrastructure
spec:
  type: ClusterIP
  ports:
  - name: ldap
    port: 389
    targetPort: 3890
    protocol: TCP
  selector:
    app.kubernetes.io/name: lldap